export default {
	anicerControl:{
		isSucceed:false,
		hasCompanyInfo:false,
		step:'identity'
	},
	anicerFormData: {
		bankAccount: '',
		bankAccountName: '',
		bankAccountPermissionImage: '',
		bankBranchAddress: '',
		bankBranchLineNumber: '',
		bankBranchName: '',
		bizEndDate: '',
		bizLicenseAddress: '',
		bizLicenseImage: '',
		bizLicenseNumber: '',
		bizScope: '',
		bizStartDate: '',
		companyAddress: '',
		companyEmail: '',
		companyFoundDate: '',
		companyName: '',
		companyNature: '2',
		companyPhone: '',
		contactAddress: '',
		contactEmail: '',
		contactMobile: '',
		contactName: '',
		contactSex: '1',
		emerContact: '',
		emerContactPhone: '',
		legalReprIdBackImage: '',
		legalReprIdImage: '',
		legalReprIdNumber: '',
		legalReprName: '',
		orgCode: '',
		orgCodeImage: '',
		regCapital: '',
		taxCode: '',
		taxNumber: '',
		taxRegCertImage: '',
		taxpayerQualificationImage: '',
		taxpayerType: ''
	}
};
