spring:
    application:
        name: dms
        serverName: dms.gomeplus.com

    profiles:
        active: production

    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: localhost
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        # 连接超时时间（毫秒）
        timeout: 0
        pool:
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: -1
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池中的最小空闲连接
            min-idle: 0

app:
    datasource:
        system:
            url: jdbc:mysql://g1mysmv1.ad.pro.gomeplus.com:3306/ams_system?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
            username: ams_user
            password: H4w9H5Ym
            driver-class-name: com.mysql.jdbc.Driver
        ad:
            url: jdbc:mysql://g1mysmv1.ad.pro.gomeplus.com:3306/ams_ad?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
            username: ams_user
            password: H4w9H5Ym
            driver-class-name: com.mysql.jdbc.Driver
        launch:
            url: jdbc:mysql://g1mysmv1.ad.pro.gomeplus.com:3306/ams_launch?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
            username: ams_user
            password: H4w9H5Ym
            driver-class-name: com.mysql.jdbc.Driver

    hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        hbm2ddl:
            auto: none
    api:
        dmpHost: http://dmpapi.pro.gomeplus.com

server:
    port: 9002
    contextPath:
